-- Updated SQL for Community Posts, Comments and Replies

-- 1. Create community_posts table
CREATE TABLE IF NOT EXISTS public.community_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    author_name TEXT NOT NULL,
    content TEXT NOT NULL,
    image_url TEXT,
    is_published BOOLEAN DEFAULT TRUE
);

-- 2. Create community_comments table (Updated with parent_id and device_id)
CREATE TABLE IF NOT EXISTS public.community_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    post_id BIGINT REFERENCES public.community_posts(id) ON DELETE CASCADE,
    parent_id BIGINT REFERENCES public.community_comments(id) ON DELETE CASCADE,
    author_name TEXT NOT NULL DEFAULT 'Subscriber',
    device_id TEXT,
    content TEXT NOT NULL
);

-- Index for faster reply lookups
CREATE INDEX IF NOT EXISTS idx_community_comments_parent_id ON public.community_comments(parent_id);
CREATE INDEX IF NOT EXISTS idx_community_comments_post_id ON public.community_comments(post_id);
